### ISSUE TITLE
Support for ADIF Broadcasts from WSJT-X (Logging & Ongoing QSOs)

### ISSUE THREAD

**Issue by besynnerlig** [tnxqso/wave-flex-integrator#1]
### Issue:

Currently, Wave-Flex-Integrator does not listen for ADIF broadcasts from WSJT-X, which means it doesn’t support logging or displaying ongoing QSOs for users who operate digital modes. Some users (including myself in the past) use WSJT-X for digital modes like FT8, and it could be helpful to integrate this feature for a more complete logging experience.

### Feature Request:

Add support for ADIF broadcasts from WSJT-X (and similar apps).
This should cover:

- Ongoing QSOs: Displaying live QSOs on the FlexRadio SmartSDR panadapter while the QSO is in progress.
- Completed QSOs: Logging the completed QSO data directly into Wavelog.

### Why it’s important:

Although I’ve personally stopped using digital modes since I got my FlexRadio and a remote QTH, many operators still rely on WSJT-X for digital communications.
Supporting ADIF broadcasts would enhance Wave-Flex-Integrator’s utility, making it a one-stop solution for logging both traditional and digital QSOs.

Looking forward to feedback and suggestions on how to implement this! 🚀

**Comment by mboroff** [comment]
Receiving UDP broadcasts is a fundamental method of application passing information across multiple platforms. Any application like WSJT-X lets other applications know their logging info through this mechanism. I strongly suggest you work on this enhancements to receive acceptance in the community.
