### ISSUE TITLE
FT8 Broadcasts from MSHV Not Recognized by Wave-Flex Integrator

### ISSUE THREAD

**Issue by DL8JJ-Emil** [tnxqso/wave-flex-integrator#27]
Hello,
I tested the integration to wsjt-x and works great.
The same i tried to do with MSHV, but no luck. The settings are fine and UDP broadcast is green and working.
Can you check this out.
Thanks.
Greetings
Emil

**Comment by besynnerlig** [comment]
Thank you so much for reporting this issue! Wave-Flex Integrator is designed specifically to listen for and parse UDP broadcasts originating from WSJT-X. According to the developer of MSHV, the broadcast messages are the same as those in WSJT-X, so it should work in theory.

However, you didn't mention if you encountered any error messages, and I haven’t received a debug log from you, which makes it tricky to pinpoint the issue. Could you kindly check which port MSHV is using for its UDP broadcasts? Make sure it matches the "UDP Listen Port" setting in Wave-Flex Integrator’s configuration. Also, ensure that "WSJT-X Integration Enabled" is set to true.

If this doesn't resolve the issue, I’d be happy to take a closer look! In that case, please send over the full debug log, and I’ll investigate further. Since Wave-Flex Integrator is successfully parsing UDP broadcasts from WSJT-X, this might be a configuration mismatch or perhaps an incompatibility.

**Comment by DL8JJ-Emil** [comment]
Here the debug fileOn MSHV / Seeings / Network options thy are on the UDP. IP Flexradio and 2237 Port. The connection is green. So when you make dobble klick on decodet radio, the wave log did not opened.On same NB wsjt-x work fine.cheersEmil

 VY 73! Emil Bergmann, de DL8JJ http://www.dl8jj.darc.de
Tel: +491794206287
 

    Am Montag, 14. Oktober 2024 um 09:52:10 MESZ hat B Synnerlig ***@***.***> Folgendes geschrieben:  
 
 


Thank you so much for reporting this issue! Wave-Flex Integrator is designed specifically to listen for and parse UDP broadcasts originating from WSJT-X. According to the developer of MSHV, the broadcast messages are the same as those in WSJT-X, so it should work in theory.

However, you didn't mention if you encountered any error messages, and I haven’t received a debug log from you, which makes it tricky to pinpoint the issue. Could you kindly check which port MSHV is using for its UDP broadcasts? Make sure it matches the "UDP Listen Port" setting in Wave-Flex Integrator’s configuration. Also, ensure that "WSJT-X Integration Enabled" is set to true.

If this doesn't resolve the issue, I’d be happy to take a closer look! In that case, please send over the full debug log, and I’ll investigate further. Since Wave-Flex Integrator is successfully parsing UDP broadcasts from WSJT-X, this might be a configuration mismatch or perhaps an incompatibility.

**Comment by DL8JJ-Emil** [comment]
Here the mshv setzingsVon meinem iPhone gesendetAm 14.10.2024 um 09:52 schrieb B Synnerlig ***@***.***>:﻿
Thank you so much for reporting this issue! Wave-Flex Integrator is designed specifically to listen for and parse UDP broadcasts originating from WSJT-X. According to the developer of MSHV, the broadcast messages are the same as those in WSJT-X, so it should work in theory.
However, you didn't mention if you encountered any error messages, and I haven’t received a debug log from you, which makes it tricky to pinpoint the issue. Could you kindly check which port MSHV is using for its UDP broadcasts? Make sure it matches the "UDP Listen Port" setting in Wave-Flex Integrator’s configuration. Also, ensure that "WSJT-X Integration Enabled" is set to true.
If this doesn't resolve the issue, I’d be happy to take a closer look! In that case, please send over the full debug log, and I’ll investigate further. Since Wave-Flex Integrator is successfully parsing UDP broadcasts from WSJT-X, this might be a configuration mismatch or perhaps an incompatibility.

**Comment by DL8JJ-Emil** [comment]
![image](https://github.com/user-attachments/assets/b838f5d2-099d-417c-9e02-0b148bc2668b)
here the settings in mshv

**Comment by besynnerlig** [comment]
It seems like you're reporting two issues with the Wave-Flex Integrators WSJT-X Integration:

1. Wave-Flex Integrator isn’t detecting active QSOs or displaying the current callsign being worked in Wavelog's live logging tab.
2. Wave-Flex Integrator isn’t logging completed QSOs from WSJT-X ADIF broadcasts directly into Wavelog.

I assume you're running MSHV on the same machine as WSJT-X (which works fine). Even though MSHV should be compatible with WSJT-X, it looks like there might be some differences causing the issue. I assume that you have already checked that the MSHV is sending BOTH the correct STATION_CALLSIGN and the STATION_GRIDSQUARE that you have set in the active Wavelog Station Location.

As I mentioned earlier, I’d be happy to take a closer look! Please send over the full debug log, and I’ll investigate further. You can find instructions on how to generate and send the debug log [here in the README](https://github.com/tnxqso/wave-flex-integrator?tab=readme-ov-file#debugging-and-troubleshooting).
